version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: eventos_culturales_db
    environment:
      POSTGRES_DB: eventos_culturales
      POSTGRES_USER: postgres  # Cambiado a postgres
      POSTGRES_PASSWORD: postgres  # Contraseña simple para pruebas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: