version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: eventos_culturales_db
    environment:
      POSTGRES_DB: eventos_culturales
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: